"""add password column to user

Revision ID: 85faac50638f
Revises: 95663173f96e
Create Date: 2020-08-15 09:30:44.445533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85faac50638f'
down_revision = '95663173f96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
