"""add confirmed attribute to user for account confirmation purpose

Revision ID: dfe5c7560d44
Revises: 8226b9ecc07a
Create Date: 2020-08-15 23:10:03.687301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe5c7560d44'
down_revision = '8226b9ecc07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
